# Generated by Django 3.1.1 on 2020-09-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200916_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('1', 'Full Time'), ('2', 'Part time'), ('3', 'Internship')], default='Full Time', max_length=10),
        ),
    ]
