# Generated by Django 3.1.1 on 2020-09-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200916_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part time', 'Part time'), ('Part time', 'Internship')], default='Full Time', max_length=10),
        ),
    ]
